# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/voyez/Documents/cpp/cworld

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/voyez/Documents/cpp/cworld

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/voyez/Documents/cpp/cworld/CMakeFiles /home/voyez/Documents/cpp/cworld/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/voyez/Documents/cpp/cworld/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cworld

# Build rule for target.
cworld: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cworld
.PHONY : cworld

# fast build rule for target.
cworld/fast:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/build
.PHONY : cworld/fast

FreeFlyCam.o: FreeFlyCam.cpp.o

.PHONY : FreeFlyCam.o

# target to build an object file
FreeFlyCam.cpp.o:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/FreeFlyCam.cpp.o
.PHONY : FreeFlyCam.cpp.o

FreeFlyCam.i: FreeFlyCam.cpp.i

.PHONY : FreeFlyCam.i

# target to preprocess a source file
FreeFlyCam.cpp.i:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/FreeFlyCam.cpp.i
.PHONY : FreeFlyCam.cpp.i

FreeFlyCam.s: FreeFlyCam.cpp.s

.PHONY : FreeFlyCam.s

# target to generate assembly for a file
FreeFlyCam.cpp.s:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/FreeFlyCam.cpp.s
.PHONY : FreeFlyCam.cpp.s

crea/crea.o: crea/crea.cpp.o

.PHONY : crea/crea.o

# target to build an object file
crea/crea.cpp.o:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/crea/crea.cpp.o
.PHONY : crea/crea.cpp.o

crea/crea.i: crea/crea.cpp.i

.PHONY : crea/crea.i

# target to preprocess a source file
crea/crea.cpp.i:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/crea/crea.cpp.i
.PHONY : crea/crea.cpp.i

crea/crea.s: crea/crea.cpp.s

.PHONY : crea/crea.s

# target to generate assembly for a file
crea/crea.cpp.s:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/crea/crea.cpp.s
.PHONY : crea/crea.cpp.s

crea/vision.o: crea/vision.cpp.o

.PHONY : crea/vision.o

# target to build an object file
crea/vision.cpp.o:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/crea/vision.cpp.o
.PHONY : crea/vision.cpp.o

crea/vision.i: crea/vision.cpp.i

.PHONY : crea/vision.i

# target to preprocess a source file
crea/vision.cpp.i:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/crea/vision.cpp.i
.PHONY : crea/vision.cpp.i

crea/vision.s: crea/vision.cpp.s

.PHONY : crea/vision.s

# target to generate assembly for a file
crea/vision.cpp.s:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/crea/vision.cpp.s
.PHONY : crea/vision.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/main.cpp.s
.PHONY : main.cpp.s

map/map.o: map/map.cpp.o

.PHONY : map/map.o

# target to build an object file
map/map.cpp.o:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/map/map.cpp.o
.PHONY : map/map.cpp.o

map/map.i: map/map.cpp.i

.PHONY : map/map.i

# target to preprocess a source file
map/map.cpp.i:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/map/map.cpp.i
.PHONY : map/map.cpp.i

map/map.s: map/map.cpp.s

.PHONY : map/map.s

# target to generate assembly for a file
map/map.cpp.s:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/map/map.cpp.s
.PHONY : map/map.cpp.s

map/planet.o: map/planet.cpp.o

.PHONY : map/planet.o

# target to build an object file
map/planet.cpp.o:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/map/planet.cpp.o
.PHONY : map/planet.cpp.o

map/planet.i: map/planet.cpp.i

.PHONY : map/planet.i

# target to preprocess a source file
map/planet.cpp.i:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/map/planet.cpp.i
.PHONY : map/planet.cpp.i

map/planet.s: map/planet.cpp.s

.PHONY : map/planet.s

# target to generate assembly for a file
map/planet.cpp.s:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/map/planet.cpp.s
.PHONY : map/planet.cpp.s

map/water.o: map/water.cpp.o

.PHONY : map/water.o

# target to build an object file
map/water.cpp.o:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/map/water.cpp.o
.PHONY : map/water.cpp.o

map/water.i: map/water.cpp.i

.PHONY : map/water.i

# target to preprocess a source file
map/water.cpp.i:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/map/water.cpp.i
.PHONY : map/water.cpp.i

map/water.s: map/water.cpp.s

.PHONY : map/water.s

# target to generate assembly for a file
map/water.cpp.s:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/map/water.cpp.s
.PHONY : map/water.cpp.s

znoise/FBM.o: znoise/FBM.cpp.o

.PHONY : znoise/FBM.o

# target to build an object file
znoise/FBM.cpp.o:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/FBM.cpp.o
.PHONY : znoise/FBM.cpp.o

znoise/FBM.i: znoise/FBM.cpp.i

.PHONY : znoise/FBM.i

# target to preprocess a source file
znoise/FBM.cpp.i:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/FBM.cpp.i
.PHONY : znoise/FBM.cpp.i

znoise/FBM.s: znoise/FBM.cpp.s

.PHONY : znoise/FBM.s

# target to generate assembly for a file
znoise/FBM.cpp.s:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/FBM.cpp.s
.PHONY : znoise/FBM.cpp.s

znoise/HybridMultiFractal.o: znoise/HybridMultiFractal.cpp.o

.PHONY : znoise/HybridMultiFractal.o

# target to build an object file
znoise/HybridMultiFractal.cpp.o:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/HybridMultiFractal.cpp.o
.PHONY : znoise/HybridMultiFractal.cpp.o

znoise/HybridMultiFractal.i: znoise/HybridMultiFractal.cpp.i

.PHONY : znoise/HybridMultiFractal.i

# target to preprocess a source file
znoise/HybridMultiFractal.cpp.i:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/HybridMultiFractal.cpp.i
.PHONY : znoise/HybridMultiFractal.cpp.i

znoise/HybridMultiFractal.s: znoise/HybridMultiFractal.cpp.s

.PHONY : znoise/HybridMultiFractal.s

# target to generate assembly for a file
znoise/HybridMultiFractal.cpp.s:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/HybridMultiFractal.cpp.s
.PHONY : znoise/HybridMultiFractal.cpp.s

znoise/MixerBase.o: znoise/MixerBase.cpp.o

.PHONY : znoise/MixerBase.o

# target to build an object file
znoise/MixerBase.cpp.o:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/MixerBase.cpp.o
.PHONY : znoise/MixerBase.cpp.o

znoise/MixerBase.i: znoise/MixerBase.cpp.i

.PHONY : znoise/MixerBase.i

# target to preprocess a source file
znoise/MixerBase.cpp.i:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/MixerBase.cpp.i
.PHONY : znoise/MixerBase.cpp.i

znoise/MixerBase.s: znoise/MixerBase.cpp.s

.PHONY : znoise/MixerBase.s

# target to generate assembly for a file
znoise/MixerBase.cpp.s:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/MixerBase.cpp.s
.PHONY : znoise/MixerBase.cpp.s

znoise/NoiseBase.o: znoise/NoiseBase.cpp.o

.PHONY : znoise/NoiseBase.o

# target to build an object file
znoise/NoiseBase.cpp.o:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/NoiseBase.cpp.o
.PHONY : znoise/NoiseBase.cpp.o

znoise/NoiseBase.i: znoise/NoiseBase.cpp.i

.PHONY : znoise/NoiseBase.i

# target to preprocess a source file
znoise/NoiseBase.cpp.i:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/NoiseBase.cpp.i
.PHONY : znoise/NoiseBase.cpp.i

znoise/NoiseBase.s: znoise/NoiseBase.cpp.s

.PHONY : znoise/NoiseBase.s

# target to generate assembly for a file
znoise/NoiseBase.cpp.s:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/NoiseBase.cpp.s
.PHONY : znoise/NoiseBase.cpp.s

znoise/NoiseTools.o: znoise/NoiseTools.cpp.o

.PHONY : znoise/NoiseTools.o

# target to build an object file
znoise/NoiseTools.cpp.o:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/NoiseTools.cpp.o
.PHONY : znoise/NoiseTools.cpp.o

znoise/NoiseTools.i: znoise/NoiseTools.cpp.i

.PHONY : znoise/NoiseTools.i

# target to preprocess a source file
znoise/NoiseTools.cpp.i:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/NoiseTools.cpp.i
.PHONY : znoise/NoiseTools.cpp.i

znoise/NoiseTools.s: znoise/NoiseTools.cpp.s

.PHONY : znoise/NoiseTools.s

# target to generate assembly for a file
znoise/NoiseTools.cpp.s:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/NoiseTools.cpp.s
.PHONY : znoise/NoiseTools.cpp.s

znoise/Perlin.o: znoise/Perlin.cpp.o

.PHONY : znoise/Perlin.o

# target to build an object file
znoise/Perlin.cpp.o:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/Perlin.cpp.o
.PHONY : znoise/Perlin.cpp.o

znoise/Perlin.i: znoise/Perlin.cpp.i

.PHONY : znoise/Perlin.i

# target to preprocess a source file
znoise/Perlin.cpp.i:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/Perlin.cpp.i
.PHONY : znoise/Perlin.cpp.i

znoise/Perlin.s: znoise/Perlin.cpp.s

.PHONY : znoise/Perlin.s

# target to generate assembly for a file
znoise/Perlin.cpp.s:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/Perlin.cpp.s
.PHONY : znoise/Perlin.cpp.s

znoise/Simplex.o: znoise/Simplex.cpp.o

.PHONY : znoise/Simplex.o

# target to build an object file
znoise/Simplex.cpp.o:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/Simplex.cpp.o
.PHONY : znoise/Simplex.cpp.o

znoise/Simplex.i: znoise/Simplex.cpp.i

.PHONY : znoise/Simplex.i

# target to preprocess a source file
znoise/Simplex.cpp.i:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/Simplex.cpp.i
.PHONY : znoise/Simplex.cpp.i

znoise/Simplex.s: znoise/Simplex.cpp.s

.PHONY : znoise/Simplex.s

# target to generate assembly for a file
znoise/Simplex.cpp.s:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/Simplex.cpp.s
.PHONY : znoise/Simplex.cpp.s

znoise/Worley.o: znoise/Worley.cpp.o

.PHONY : znoise/Worley.o

# target to build an object file
znoise/Worley.cpp.o:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/Worley.cpp.o
.PHONY : znoise/Worley.cpp.o

znoise/Worley.i: znoise/Worley.cpp.i

.PHONY : znoise/Worley.i

# target to preprocess a source file
znoise/Worley.cpp.i:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/Worley.cpp.i
.PHONY : znoise/Worley.cpp.i

znoise/Worley.s: znoise/Worley.cpp.s

.PHONY : znoise/Worley.s

# target to generate assembly for a file
znoise/Worley.cpp.s:
	$(MAKE) -f CMakeFiles/cworld.dir/build.make CMakeFiles/cworld.dir/znoise/Worley.cpp.s
.PHONY : znoise/Worley.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cworld"
	@echo "... FreeFlyCam.o"
	@echo "... FreeFlyCam.i"
	@echo "... FreeFlyCam.s"
	@echo "... crea/crea.o"
	@echo "... crea/crea.i"
	@echo "... crea/crea.s"
	@echo "... crea/vision.o"
	@echo "... crea/vision.i"
	@echo "... crea/vision.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... map/map.o"
	@echo "... map/map.i"
	@echo "... map/map.s"
	@echo "... map/planet.o"
	@echo "... map/planet.i"
	@echo "... map/planet.s"
	@echo "... map/water.o"
	@echo "... map/water.i"
	@echo "... map/water.s"
	@echo "... znoise/FBM.o"
	@echo "... znoise/FBM.i"
	@echo "... znoise/FBM.s"
	@echo "... znoise/HybridMultiFractal.o"
	@echo "... znoise/HybridMultiFractal.i"
	@echo "... znoise/HybridMultiFractal.s"
	@echo "... znoise/MixerBase.o"
	@echo "... znoise/MixerBase.i"
	@echo "... znoise/MixerBase.s"
	@echo "... znoise/NoiseBase.o"
	@echo "... znoise/NoiseBase.i"
	@echo "... znoise/NoiseBase.s"
	@echo "... znoise/NoiseTools.o"
	@echo "... znoise/NoiseTools.i"
	@echo "... znoise/NoiseTools.s"
	@echo "... znoise/Perlin.o"
	@echo "... znoise/Perlin.i"
	@echo "... znoise/Perlin.s"
	@echo "... znoise/Simplex.o"
	@echo "... znoise/Simplex.i"
	@echo "... znoise/Simplex.s"
	@echo "... znoise/Worley.o"
	@echo "... znoise/Worley.i"
	@echo "... znoise/Worley.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

